title: Joaquín Romero • Data Analytics Portfolio
author: Joaquín Romero Pérez
email: j.romero@email.com
description: Personal portfolio showcasing bootcamp projects, Streamlit apps and modular analytics pipelines.

theme: minima

minima:
  skin: classic
  nav_pages:
    - README.md
  social_links: []

sass:
  style: compressed
